# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lane_map.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# ValidateProtobufRuntimeVersion call removed for compatibility
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import map_pb2 as map__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elane_map.proto\x12\x0bhumex.proto\x1a\tmap.proto\"\x8e\x04\n\x0bLaneMapLane\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cis_connector\x18\x02 \x01(\x08\x12-\n\x0b\x63\x65nter_line\x18\x03 \x03(\x0b\x32\x18.humex.proto.SegmentData\x12\x16\n\x0ewidth_estimate\x18\x04 \x01(\x01\x12\x15\n\rnext_lane_ids\x18\x05 \x03(\x05\x12\x15\n\rprev_lane_ids\x18\x06 \x03(\x05\x12\x15\n\rleft_lane_ids\x18\x07 \x03(\x05\x12\x16\n\x0eright_lane_ids\x18\x08 \x03(\x05\x12(\n\tturn_type\x18\t \x01(\x0e\x32\x15.humex.proto.TurnType\x12*\n\nstop_point\x18\n \x01(\x0b\x32\x16.humex.proto.PointData\x12\x15\n\rhas_stop_sign\x18\x0b \x01(\x08\x12\x16\n\x0esource_lane_id\x18\x0c \x01(\x05\x12\x0f\n\x07s_start\x18\r \x01(\x01\x12\r\n\x05s_end\x18\x0e \x01(\x01\x12\x1c\n\x14overlapping_lane_ids\x18\x0f \x03(\x05\x12\x13\n\x0b\x63orridor_id\x18\x10 \x01(\x05\x12/\n\rleft_boundary\x18\x11 \x03(\x0b\x32\x18.humex.proto.SegmentData\x12\x30\n\x0eright_boundary\x18\x12 \x03(\x0b\x32\x18.humex.proto.SegmentData\"V\n\x0cIntersection\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08lane_ids\x18\x02 \x03(\x05\x12(\n\x08\x63\x65ntroid\x18\x03 \x01(\x0b\x32\x16.humex.proto.PointData\"\x89\x02\n\x0bLaneMapData\x12\x19\n\x11\x61lgorithm_version\x18\x01 \x01(\t\x12\x17\n\x0fsource_map_name\x18\x02 \x01(\t\x12\x18\n\x10\x62uilt_at_unix_ns\x18\x03 \x01(\x03\x12\x32\n\x05lanes\x18\x04 \x03(\x0b\x32#.humex.proto.LaneMapData.LanesEntry\x12\x30\n\rintersections\x18\x05 \x03(\x0b\x32\x19.humex.proto.Intersection\x1a\x46\n\nLanesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.humex.proto.LaneMapLane:\x02\x38\x01*_\n\x08TurnType\x12\x10\n\x0cTURN_UNKNOWN\x10\x00\x12\x11\n\rTURN_STRAIGHT\x10\x01\x12\r\n\tTURN_LEFT\x10\x02\x12\x0e\n\nTURN_RIGHT\x10\x03\x12\x0f\n\x0bTURN_U_TURN\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lane_map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LANEMAPDATA_LANESENTRY']._loaded_options = None
  _globals['_LANEMAPDATA_LANESENTRY']._serialized_options = b'8\001'
  _globals['_TURNTYPE']._serialized_start=927
  _globals['_TURNTYPE']._serialized_end=1022
  _globals['_LANEMAPLANE']._serialized_start=43
  _globals['_LANEMAPLANE']._serialized_end=569
  _globals['_INTERSECTION']._serialized_start=571
  _globals['_INTERSECTION']._serialized_end=657
  _globals['_LANEMAPDATA']._serialized_start=660
  _globals['_LANEMAPDATA']._serialized_end=925
  _globals['_LANEMAPDATA_LANESENTRY']._serialized_start=855
  _globals['_LANEMAPDATA_LANESENTRY']._serialized_end=925
# @@protoc_insertion_point(module_scope)
