# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# ValidateProtobufRuntimeVersion call removed for compatibility
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmap.proto\x12\x0bhumex.proto\",\n\tPointData\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"5\n\x0bSegmentData\x12&\n\x06points\x18\x01 \x03(\x0b\x32\x16.humex.proto.PointData\"\x80\x02\n\x08LaneData\x12\n\n\x02id\x18\x01 \x01(\x05\x12-\n\x0b\x63\x65nter_line\x18\x02 \x03(\x0b\x32\x18.humex.proto.SegmentData\x12/\n\rleft_boundary\x18\x03 \x03(\x0b\x32\x18.humex.proto.SegmentData\x12\x30\n\x0eright_boundary\x18\x04 \x03(\x0b\x32\x18.humex.proto.SegmentData\x12\x13\n\x0bspeed_limit\x18\x05 \x01(\x01\x12*\n\nstop_point\x18\x06 \x01(\x0b\x32\x16.humex.proto.PointData\x12\x15\n\rhas_stop_sign\x18\x07 \x01(\x08\">\n\x0fLaneConnections\x12\x0f\n\x07lane_id\x18\x01 \x01(\x05\x12\x1a\n\x12\x63onnected_lane_ids\x18\x02 \x03(\x05\"\xfe\x02\n\x07MapData\x12.\n\x05lanes\x18\x01 \x03(\x0b\x32\x1f.humex.proto.MapData.LanesEntry\x12\x30\n\nnext_lanes\x18\x02 \x03(\x0b\x32\x1c.humex.proto.LaneConnections\x12\x30\n\nprev_lanes\x18\x03 \x03(\x0b\x32\x1c.humex.proto.LaneConnections\x12\x30\n\nleft_lanes\x18\x04 \x03(\x0b\x32\x1c.humex.proto.LaneConnections\x12\x31\n\x0bright_lanes\x18\x05 \x03(\x0b\x32\x1c.humex.proto.LaneConnections\x12\x10\n\x08map_name\x18\x06 \x01(\t\x12\x0f\n\x07version\x18\x07 \x01(\x01\x12\x12\n\ncreated_at\x18\x08 \x01(\t\x1a\x43\n\nLanesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.humex.proto.LaneData:\x02\x38\x01\";\n\x03Map\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\x08map_data\x18\x02 \x01(\x0b\x32\x14.humex.proto.MapDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPDATA_LANESENTRY']._loaded_options = None
  _globals['_MAPDATA_LANESENTRY']._serialized_options = b'8\001'
  _globals['_POINTDATA']._serialized_start=26
  _globals['_POINTDATA']._serialized_end=70
  _globals['_SEGMENTDATA']._serialized_start=72
  _globals['_SEGMENTDATA']._serialized_end=125
  _globals['_LANEDATA']._serialized_start=128
  _globals['_LANEDATA']._serialized_end=384
  _globals['_LANECONNECTIONS']._serialized_start=386
  _globals['_LANECONNECTIONS']._serialized_end=448
  _globals['_MAPDATA']._serialized_start=451
  _globals['_MAPDATA']._serialized_end=833
  _globals['_MAPDATA_LANESENTRY']._serialized_start=766
  _globals['_MAPDATA_LANESENTRY']._serialized_end=833
  _globals['_MAP']._serialized_start=835
  _globals['_MAP']._serialized_end=894
# @@protoc_insertion_point(module_scope)
