# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metric_dag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# ValidateProtobufRuntimeVersion call removed for compatibility
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10metric_dag.proto\x12\x0bhumex.proto\"\xc9\x01\n\tNodeProto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0e\n\x06inputs\x18\x05 \x03(\x05\x12\x32\n\x06params\x18\x06 \x03(\x0b\x32\".humex.proto.NodeProto.ParamsEntry\x12\x0c\n\x04tags\x18\x07 \x03(\t\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"=\n\x11MetricDAGMetadata\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x13\n\x0bsource_file\x18\x02 \x01(\t\"\xbf\x01\n\x0eMetricDAGProto\x12\x35\n\x05nodes\x18\x01 \x03(\x0b\x32&.humex.proto.MetricDAGProto.NodesEntry\x12\x30\n\x08metadata\x18\x02 \x01(\x0b\x32\x1e.humex.proto.MetricDAGMetadata\x1a\x44\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.humex.proto.NodeProto:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metric_dag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEPROTO_PARAMSENTRY']._loaded_options = None
  _globals['_NODEPROTO_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_METRICDAGPROTO_NODESENTRY']._loaded_options = None
  _globals['_METRICDAGPROTO_NODESENTRY']._serialized_options = b'8\001'
  _globals['_NODEPROTO']._serialized_start=34
  _globals['_NODEPROTO']._serialized_end=235
  _globals['_NODEPROTO_PARAMSENTRY']._serialized_start=190
  _globals['_NODEPROTO_PARAMSENTRY']._serialized_end=235
  _globals['_METRICDAGMETADATA']._serialized_start=237
  _globals['_METRICDAGMETADATA']._serialized_end=298
  _globals['_METRICDAGPROTO']._serialized_start=301
  _globals['_METRICDAGPROTO']._serialized_end=492
  _globals['_METRICDAGPROTO_NODESENTRY']._serialized_start=424
  _globals['_METRICDAGPROTO_NODESENTRY']._serialized_end=492
# @@protoc_insertion_point(module_scope)
