# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# ValidateProtobufRuntimeVersion call removed for compatibility
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\x12\x0bhumex.proto\"c\n\x10RobotDescription\x12\x11\n\tobject_id\x18\x01 \x01(\x05\x12\x11\n\turdf_path\x18\x02 \x01(\t\x12\x13\n\x0bjoint_names\x18\x03 \x03(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\"u\n\nRobotState\x12\x11\n\tobject_id\x18\x01 \x01(\x05\x12\x1b\n\x0fjoint_positions\x18\x02 \x03(\x01\x42\x02\x10\x01\x12\x1c\n\x10joint_velocities\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x19\n\rjoint_efforts\x18\x04 \x03(\x01\x42\x02\x10\x01\"\xa6\x01\n\nRobotFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12:\n\nrobot_list\x18\x02 \x03(\x0b\x32&.humex.proto.RobotFrame.RobotListEntry\x1aI\n\x0eRobotListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.humex.proto.RobotState:\x02\x38\x01\"\x89\x02\n\tRobotData\x12\x32\n\x06roster\x18\x01 \x03(\x0b\x32\".humex.proto.RobotData.RosterEntry\x12\x32\n\x06\x66rames\x18\x02 \x03(\x0b\x32\".humex.proto.RobotData.FramesEntry\x1aL\n\x0bRosterEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.humex.proto.RobotDescription:\x02\x38\x01\x1a\x46\n\x0b\x46ramesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.humex.proto.RobotFrame:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTSTATE'].fields_by_name['joint_positions']._loaded_options = None
  _globals['_ROBOTSTATE'].fields_by_name['joint_positions']._serialized_options = b'\020\001'
  _globals['_ROBOTSTATE'].fields_by_name['joint_velocities']._loaded_options = None
  _globals['_ROBOTSTATE'].fields_by_name['joint_velocities']._serialized_options = b'\020\001'
  _globals['_ROBOTSTATE'].fields_by_name['joint_efforts']._loaded_options = None
  _globals['_ROBOTSTATE'].fields_by_name['joint_efforts']._serialized_options = b'\020\001'
  _globals['_ROBOTFRAME_ROBOTLISTENTRY']._loaded_options = None
  _globals['_ROBOTFRAME_ROBOTLISTENTRY']._serialized_options = b'8\001'
  _globals['_ROBOTDATA_ROSTERENTRY']._loaded_options = None
  _globals['_ROBOTDATA_ROSTERENTRY']._serialized_options = b'8\001'
  _globals['_ROBOTDATA_FRAMESENTRY']._loaded_options = None
  _globals['_ROBOTDATA_FRAMESENTRY']._serialized_options = b'8\001'
  _globals['_ROBOTDESCRIPTION']._serialized_start=28
  _globals['_ROBOTDESCRIPTION']._serialized_end=127
  _globals['_ROBOTSTATE']._serialized_start=129
  _globals['_ROBOTSTATE']._serialized_end=246
  _globals['_ROBOTFRAME']._serialized_start=249
  _globals['_ROBOTFRAME']._serialized_end=415
  _globals['_ROBOTFRAME_ROBOTLISTENTRY']._serialized_start=342
  _globals['_ROBOTFRAME_ROBOTLISTENTRY']._serialized_end=415
  _globals['_ROBOTDATA']._serialized_start=418
  _globals['_ROBOTDATA']._serialized_end=683
  _globals['_ROBOTDATA_ROSTERENTRY']._serialized_start=535
  _globals['_ROBOTDATA_ROSTERENTRY']._serialized_end=611
  _globals['_ROBOTDATA_FRAMESENTRY']._serialized_start=613
  _globals['_ROBOTDATA_FRAMESENTRY']._serialized_end=683
# @@protoc_insertion_point(module_scope)
