# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# ValidateProtobufRuntimeVersion call removed for compatibility
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csignal.proto\x12\x0bhumex.proto\"\xc0\x02\n\x0bSignalState\x12\x0f\n\x07lane_id\x18\x01 \x01(\x05\x12-\n\x05state\x18\x02 \x01(\x0e\x32\x1e.humex.proto.SignalState.State\"\xf0\x01\n\x05State\x12\x16\n\x12LANE_STATE_UNKNOWN\x10\x00\x12\x19\n\x15LANE_STATE_ARROW_STOP\x10\x01\x12\x1c\n\x18LANE_STATE_ARROW_CAUTION\x10\x02\x12\x17\n\x13LANE_STATE_ARROW_GO\x10\x03\x12\x13\n\x0fLANE_STATE_STOP\x10\x04\x12\x16\n\x12LANE_STATE_CAUTION\x10\x05\x12\x11\n\rLANE_STATE_GO\x10\x06\x12\x1c\n\x18LANE_STATE_FLASHING_STOP\x10\x07\x12\x1f\n\x1bLANE_STATE_FLASHING_CAUTION\x10\x08\"P\n\x0bSignalFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12.\n\x0clane_signals\x18\x02 \x03(\x0b\x32\x18.humex.proto.SignalState\"K\n\nSignalData\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\x12(\n\x06\x66rames\x18\x02 \x03(\x0b\x32\x18.humex.proto.SignalFrameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALSTATE']._serialized_start=30
  _globals['_SIGNALSTATE']._serialized_end=350
  _globals['_SIGNALSTATE_STATE']._serialized_start=110
  _globals['_SIGNALSTATE_STATE']._serialized_end=350
  _globals['_SIGNALFRAME']._serialized_start=352
  _globals['_SIGNALFRAME']._serialized_end=432
  _globals['_SIGNALDATA']._serialized_start=434
  _globals['_SIGNALDATA']._serialized_end=509
# @@protoc_insertion_point(module_scope)
